FROM node:22.12.0

# Crear directorio de trabajo
WORKDIR /app

# Copiar solo package.json y lock para aprovechar cache de Docker
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Exponer el puerto en el que corre React (normalmente 3000, no 7000)
EXPOSE 7000

# Comando para iniciar en modo desarrollo
CMD ["npm", "start"]
