FROM node:22.12.0

ENV DEBIAN_FRONTEND=noninteractive

# Crear usuario no-root
RUN adduser --disabled-password --gecos "" appuser

# Instalar dependencias necesarias del sistema
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgdk-pixbuf2.0-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    libxshmfence1 \
    libglu1-mesa \
    libpangocairo-1.0-0 \
    libpango-1.0-0 \
    --no-install-recommends

# Descargar e instalar Google Chrome estable
RUN wget -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt-get install -y /tmp/chrome.deb && \
    rm /tmp/chrome.deb

# Limpiar caché de apt
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Establecer carpeta de trabajo y copiar archivos
WORKDIR /app
COPY . .

# ✅ Cambiar permisos del directorio al usuario no-root
RUN chown -R appuser:appuser /app

# Instalar dependencias Node como root antes de cambiar de usuario
RUN npm install -g nodemon


# ✅ Cambiar al nuevo usuario no-root
USER appuser

EXPOSE 4000
CMD ["nodemon", "index.js"]
